### ISSUE TITLE
Adding any pojo entity to response in exception mapper fails if originally called resource should produce a list of pojos

### ISSUE THREAD

**Issue by glassfishrobot** [javaee/jersey#2566]
After updating from Jersey 2.3.1 to 2.5, adding a pojo entity to response in exception mapper fails for resources that originally return a List (or more likely a ParameterizedType?).

I'm attaching a sample project with the following resources available.
With version 2.3.1 the following calls produce the expected result, with version 2.5 the last one will fail.

```
curl http://localhost:8080/jackson/sample/object/1 ; echo ""
curl http://localhost:8080/jackson/sample/object/2 ; echo ""
curl http://localhost:8080/jackson/sample/list/1 ; echo ""
curl http://localhost:8080/jackson/sample/list/2 ; echo ""
```

After looking into the logged errors (with level FINE) the following information is revealed:

```
Dec 31, 2013 10:46:49 AM org.glassfish.grizzly.http.server.HttpHandler$1 run
FINE: service exception
org.glassfish.jersey.server.internal.process.MappableException: org.codehaus.jackson.map.JsonMappingException: Incompatible types: declared root type ([collection type; class java.util.List, contains [simple type, class java.lang.String]]) vs org.gla
ssfish.jersey.examples.jackson.ErrorResponse
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:96)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:149)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1139)
	at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:574)
	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:381)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:421)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:265)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:318)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:236)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1010)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:363)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:217)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	at java.lang.Thread.run(Thread.java:722)
Caused by: org.codehaus.jackson.map.JsonMappingException: Incompatible types: declared root type ([collection type; class java.util.List, contains [simple type, class java.lang.String]]) vs org.glassfish.jersey.examples.jackson.ErrorResponse
	at org.codehaus.jackson.map.ser.StdSerializerProvider._reportIncompatibleRootType(StdSerializerProvider.java:687)
	at org.codehaus.jackson.map.ser.StdSerializerProvider._serializeValue(StdSerializerProvider.java:647)
	at org.codehaus.jackson.map.ser.StdSerializerProvider.serializeValue(StdSerializerProvider.java:271)
	at org.codehaus.jackson.map.ObjectWriter.writeValue(ObjectWriter.java:325)
	at org.codehaus.jackson.jaxrs.JacksonJsonProvider.writeTo(JacksonJsonProvider.java:557)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:243)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:230)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:149)
	at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:103)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:149)
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:88)
	... 19 more
```
#### Affected Versions
[2.5]
